# Generated by Django 6.0.6 on 2026-06-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('working_directory', models.CharField(max_length=500)),
                ('system_prompt', models.TextField(blank=True)),
                ('use_git', models.BooleanField(default=False)),
                ('use_shell', models.BooleanField(default=False)),
                ('use_mcp', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
