# Generated by Django 6.0.6 on 2026-06-15 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('schedule_type', models.CharField(choices=[('interval', 'Interval'), ('cron', 'Cron')], default='interval', max_length=10)),
                ('interval_minutes', models.PositiveIntegerField(blank=True, help_text='Run every N minutes', null=True)),
                ('cron_expression', models.CharField(blank=True, help_text='Standard 5-field cron expression, e.g. 0 9 * * 1', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='agents.agent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
