# Generated by Django 6.0.6 on 2026-06-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_add_agent_run'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='use_git',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='use_mcp',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='use_shell',
        ),
        migrations.AddField(
            model_name='agent',
            name='mcp_servers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
