# Generated by Django 6.0.6 on 2026-06-15 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='claude_session_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
