# Generated by Django 6.0.6 on 2026-06-19 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0006_add_claude_session_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommandSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("command_key", models.CharField(max_length=100)),
                ("params", models.JSONField(blank=True, default=dict)),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[("interval", "Interval"), ("cron", "Cron")],
                        default="interval",
                        max_length=10,
                    ),
                ),
                (
                    "interval_minutes",
                    models.PositiveIntegerField(
                        blank=True, help_text="Run every N minutes", null=True
                    ),
                ),
                (
                    "cron_expression",
                    models.CharField(
                        blank=True,
                        help_text="Standard 5-field cron expression, e.g. 0 9 * * 1",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommandRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("command_key", models.CharField(max_length=100)),
                ("params", models.JSONField(blank=True, default=dict)),
                ("output", models.TextField(blank=True)),
                ("error", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=10,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        to="agents.commandschedule",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
