# Generated by Codex on 2026-06-19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0007_commandschedule_commandrun"),
        ("ops", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name="CommandRun"),
                migrations.DeleteModel(name="CommandSchedule"),
            ],
        ),
    ]
