# Generated by Django 6.0.6 on 2026-06-20 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LockMonitorCapture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_host", models.CharField(db_index=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=10,
                    ),
                ),
                ("data_source_count", models.PositiveIntegerField(default=0)),
                ("process_count", models.PositiveIntegerField(default=0)),
                ("lock_count", models.PositiveIntegerField(default=0)),
                ("warning", models.TextField(blank=True)),
                ("error", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="LockMonitoringRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[("process", "Process"), ("lock_wait", "Lock wait")],
                        max_length=20,
                    ),
                ),
                ("region", models.CharField(blank=True, max_length=100)),
                ("database_server_url", models.CharField(max_length=500)),
                ("schema_name", models.CharField(db_index=True, max_length=255)),
                ("process_id", models.BigIntegerField(blank=True, null=True)),
                ("waiting_process_id", models.BigIntegerField(blank=True, null=True)),
                ("blocking_process_id", models.BigIntegerField(blank=True, null=True)),
                ("user", models.CharField(blank=True, max_length=255)),
                ("host", models.CharField(blank=True, max_length=500)),
                ("database_name", models.CharField(blank=True, max_length=255)),
                ("command", models.CharField(blank=True, max_length=100)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("state", models.CharField(blank=True, max_length=500)),
                ("query_text", models.TextField(blank=True)),
                ("blocking_query_text", models.TextField(blank=True)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("captured_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "capture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="ops.lockmonitorcapture",
                    ),
                ),
            ],
            options={
                "db_table": "lock_monitoring_table",
                "ordering": ["-captured_at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["record_type", "captured_at"],
                        name="lock_monito_record__f2d160_idx",
                    ),
                    models.Index(
                        fields=["database_server_url", "schema_name"],
                        name="lock_monito_databas_3e3884_idx",
                    ),
                ],
            },
        ),
    ]
