# Generated by Django 6.0.6 on 2026-06-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops", "0002_lockmonitorcapture_lockmonitoringrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="lockmonitoringrecord",
            name="explain_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="lockmonitoringrecord",
            name="explain_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lockmonitoringrecord",
            name="explain_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lockmonitoringrecord",
            name="explanation",
            field=models.TextField(blank=True),
        ),
    ]
