# Generated by Django 6.0.6 on 2026-06-20 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops", "0003_lockmonitoringrecord_explain_error_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lockmonitorcapture",
            name="command_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lock_monitor_captures",
                to="ops.commandrun",
            ),
        ),
    ]
