# Generated by Django 6.0.6 on 2026-06-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops", "0004_lockmonitorcapture_command_run"),
    ]

    operations = [
        migrations.AddField(
            model_name="lockmonitoringrecord",
            name="contention_signals",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="lockmonitoringrecord",
            name="explain_skipped_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="lockmonitoringrecord",
            name="is_lock_blocking",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lockmonitoringrecord",
            name="is_lock_waiting",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lockmonitoringrecord",
            name="is_long_running",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lockmonitoringrecord",
            name="is_tenant_schema",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lockmonitoringrecord",
            name="server_metrics",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="lockmonitoringrecord",
            name="statement_metrics",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="lockmonitoringrecord",
            name="record_type",
            field=models.CharField(
                choices=[
                    ("process", "Process"),
                    ("lock_wait", "Lock wait"),
                    ("resource", "Resource snapshot"),
                ],
                max_length=20,
            ),
        ),
    ]
